### import nessesary library

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from path import Path
import re
import requests
import io
import json
%matplotlib inline

In [30]:
main_path = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series'

In [ ]:
case = ['confirmed','deaths','recovered']
prefix = 'time_series_covid19_'
backfix = '_global.csv'

In [31]:
confirmed_url = main_path+'/time_series_covid19_confirmed_global.csv'
death_url = main_path+'/time_series_covid19_deaths_global.csv'
recovered_url = main_path+'/time_series_covid19_recovered_global.csv'

In [32]:
s1 = requests.get(confirmed_url).content
s2 = requests.get(death_url).content
s3 = requests.get(recovered_url).content

In [35]:
confirmed_df =pd.read_csv(io.StringIO(s1.decode('utf-8')))
death_df =pd.read_csv(io.StringIO(s2.decode('utf-8')))
recovered_df =pd.read_csv(io.StringIO(s3.decode('utf-8')))

In [36]:
death_df

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,3/20/20,3/21/20,3/22/20,3/23/20,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20
0,NaN,Afghanistan,33.000000,65.000000,0,0,0,0,0,0,...,0,0,1,1,1,2,4,4,4,4
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,2,2,2,4,5,5,6,8,10,10
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,11,15,17,17,19,21,25,26,29,31
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,0,0,1,1,1,1,3,3,3,6
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,3,4,4,4,6,8,9,13,18,19
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,3
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,6,6,6,6,7,7,7,7,8,8
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Queensland,Australia,-28.016700,153.400000,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,2
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,Tasmania,Australia,-41.454500,145.970700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,0,0,0,0,0,0,3,3,3,4
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,1,1,1,1,1,1,2,2,2,2
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,6,8,16,21,28,30,49,58,68,86
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,1,1,1,1,1,2,3,3,4,4
18,NaN,Bahamas,25.034300,-77.396300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,1,1,2,2,3,4,4,4,4,4
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,1,2,2,3,4,5,5,5,5,5
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,NaN,Belgium,50.833300,4.000000,0,0,0,0,0,0,...,37,67,75,88,122,178,220,289,353,431
24,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,0,1,1,1,3,3,3,4,5,6
28,NaN,Brazil,-14.235000,-51.925300,0,0,0,0,0,0,...,11,15,25,34,46,59,77,92,111,136
29,NaN,Brunei,4.535300,114.727700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,177,233,281,335,422,465,578,759,1019,1228
224,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
225,NaN,US,37.090200,-95.712900,0,0,0,0,0,0,...,244,307,417,557,706,942,1209,1581,2026,2467
226,NaN,Uzbekistan,41.377500,64.585300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,2,2
227,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,2,2
228,NaN,Vietnam,16.000000,108.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
229,NaN,Zambia,-15.416700,28.283300,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230,NaN,Zimbabwe,-20.000000,30.000000,0,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,1
231,Diamond Princess,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
232,NaN,Dominica,15.415000,-61.371000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
233,NaN,Grenada,12.116500,-61.679000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
234,NaN,Mozambique,-18.665695,35.529562,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
235,NaN,Syria,34.802075,38.996815,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
236,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
237,NaN,Belize,13.193900,-59.543200,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,Recovered,Canada,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
239,NaN,Laos,19.856270,102.495496,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240,NaN,Libya,26.335100,17.228331,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
241,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
242,NaN,Guinea-Bissau,11.803700,-15.180400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
243,NaN,Mali,17.570692,-3.996166,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
244,NaN,Saint Kitts and Nevis,17.357822,-62.782998,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
245,Northwest Territories,Canada,64.825500,-124.845700,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
246,Yukon,Canada,64.282300,-135.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247,NaN,Kosovo,42.602636,20.902977,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1
248,NaN,Burma,21.916200,95.956000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
252,NaN,MS Zaandam,0.000000,0.000000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0